### ISSUE TITLE
Sol menünün düzenlenmesi ( işlemlerimizi bu menüye tıklayarak gideceğiz )

### ISSUE THREAD

**Issue by yakintech** [yakintech/NeveraPortal#6]
<img width="237" alt="image" src="https://github.com/yakintech/NeveraPortal/assets/16878108/c41f3d65-c125-4672-a551-945b14ce6ac6">

**Comment by birkankaraer** [comment]
![npadminpanel](https://github.com/yakintech/NeveraPortal/assets/139279313/6e0639fc-23e3-49e4-bc42-d1e6657de247)
